# Generated by Django 4.1.2 on 2022-11-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
    ]
